# Use case configuration for Nothing Phone (1)
# Author: Danila Tikhonov <danila@jiaxyga.com>

SectionVerb {
	EnableSequence [
		# Speaker & Earpiece playback
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		# Speaker & Earpiece playback
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speakers" {
	Comment "Speaker & Earpiece playback"
	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
	}
}
