# Use case configuration for Nothing Phone (1)
# Author: Danila Tikhonov <danila@jiaxyga.com>

Syntax 3

SectionUseCase."HiFi" {
        File "/Nothing/spacewar/HiFi.conf"
        Comment "HiFi quality Music."
}